# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/deck/USD00/development/tellurian/lifelogger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/deck/development/tellurian/lifelogger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	cd /home/deck/development/tellurian/lifelogger && $(CMAKE_COMMAND) -E cmake_progress_start /home/deck/development/tellurian/lifelogger/CMakeFiles /home/deck/development/tellurian/lifelogger/LL-journal//CMakeFiles/progress.marks
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/deck/development/tellurian/lifelogger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/deck/development/tellurian/lifelogger && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
LL-journal/CMakeFiles/ll-journal.dir/rule:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/CMakeFiles/ll-journal.dir/rule
.PHONY : LL-journal/CMakeFiles/ll-journal.dir/rule

# Convenience name for target.
ll-journal: LL-journal/CMakeFiles/ll-journal.dir/rule
.PHONY : ll-journal

# fast build rule for target.
ll-journal/fast:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f LL-journal/CMakeFiles/ll-journal.dir/build.make LL-journal/CMakeFiles/ll-journal.dir/build
.PHONY : ll-journal/fast

# Convenience name for target.
LL-journal/CMakeFiles/ll-journal-clean.dir/rule:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LL-journal/CMakeFiles/ll-journal-clean.dir/rule
.PHONY : LL-journal/CMakeFiles/ll-journal-clean.dir/rule

# Convenience name for target.
ll-journal-clean: LL-journal/CMakeFiles/ll-journal-clean.dir/rule
.PHONY : ll-journal-clean

# fast build rule for target.
ll-journal-clean/fast:
	cd /home/deck/development/tellurian/lifelogger && $(MAKE) $(MAKESILENT) -f LL-journal/CMakeFiles/ll-journal-clean.dir/build.make LL-journal/CMakeFiles/ll-journal-clean.dir/build
.PHONY : ll-journal-clean/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ll-journal"
	@echo "... ll-journal-clean"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/deck/development/tellurian/lifelogger && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

